#! /bin/bash

SERVER_ENV=$1
: ${SERVER_ENV:=local}

if [ "$SERVER_ENV" == "local" ]
then
   echo "In Local Environment"
   npm install
   ./node_modules/.bin/gulp --production
   php artisan serve
fi
